### ISSUE TITLE
Many connection errors continuously

### ISSUE THREAD

**Issue by kaname-png** [Deivu/Harusame#4]
When I connect with the Harusame client to Listen.moe, minutes later I get this huge amount of connection errors continuously without stopping.

The error reads as follows:
```bash
..... Error: No websocket available.
```

![image](https://user-images.githubusercontent.com/56084970/115447755-18700580-a1d6-11eb-8801-d47f7e55ffac.png)

![image](https://user-images.githubusercontent.com/56084970/115447182-69332e80-a1d5-11eb-9726-cf0fbf937fc5.png)

![image](https://user-images.githubusercontent.com/56084970/115449589-435b5900-a1d8-11eb-9355-a99c999f92cb.png)

![image](https://user-images.githubusercontent.com/56084970/115447418-ba432280-a1d5-11eb-8712-47d9d5353462.png)

**Comment by Deivu** [comment]
Could you install the latest commits directly and see if this fixes the issue @kaname-png

**Comment by kaname-png** [comment]
I don't seem to get the previous error anymore but now I get this error constantly every time I start my server
```ts
Client network socket disconnected before secure TLS connection was established
```
```ts
Connection closed code 1006
```
![image](https://user-images.githubusercontent.com/56084970/115947596-04eac600-a486-11eb-8ce4-ba5455d4c3f4.png)

**Comment by Deivu** [comment]
Could you check what commit you are running

**Comment by Deivu** [comment]
as far as my testing goes, at least my beta instance stopped throwing that errors

**Comment by kaname-png** [comment]
> Could you check what commit you are running
> 

I am using the master branch

```json
{
  "harusame": "Deivu/Harusame#master"
}
```

**Comment by Deivu** [comment]
Add a commit on installing Harusame to ensure you are locked on the latest version / commit, doing it like that can make npm think you are already on latest version, since you are just specifying to install master branch, regardless of what commit the master branch is on vs the one on your node_modules. You can do so by doing 
`github:Deivu/Harusame#30c5349b4c81bdb55de4a58c7dbce5dfeaea0f40`

**Comment by kaname-png** [comment]
It doesn't matter if I use yarn? Does the same thing happen?

**Comment by Deivu** [comment]
I'm not sure about yarn, but since you seem to be not locking into latest commit, then most likely you need to specify a commit hash

**Comment by kaname-png** [comment]
I tried it but I keep getting the same error when I start harusame
```json
{
 "harusame": "Deivu/Harusame#30c5349b4c81bdb55de4a58c7dbce5dfeaea0f40"
}
```
```ts
Error: Client network socket disconnected before secure TLS connection was established
```
```ts
Error: Client network socket disconnected before secure TLS connection was established
```
![image](https://user-images.githubusercontent.com/56084970/116582972-1b07e480-a8d3-11eb-921d-b3fb17f777f9.png)

**Comment by Deivu** [comment]
check your node_modules and check your package.json

**Comment by kaname-png** [comment]
I have already done it, I even deleted the node_modules folder but the error persists

**Comment by Deivu** [comment]
could you show me the files on your harusame on node_modules? I've been running this latest master commits for 2 days now without those errors

**Comment by kaname-png** [comment]
![image](https://user-images.githubusercontent.com/56084970/117341763-bebb3c80-ae5f-11eb-85da-56bd2513dd27.png)

**Comment by Deivu** [comment]
Could you provide me a stack trace for this error?

**Comment by kaname-png** [comment]
How do I do that?

**Comment by Deivu** [comment]
> How do I do that? 
error emits an error object, means if you log it with console.error directly it should give a stack trace

**Comment by kaname-png** [comment]
No, the event only gives me the error message and not the error object

**Comment by Deivu** [comment]
@kaname-png it should be
```js
harusame.on('error', (_,  errror) => console.error(error));
```
your code transforms the error to a string

**Comment by kaname-png** [comment]
@Deivu I have obtained this result with the code you mention
```bash
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'listen.moe',
  port: 443,
  localAddress: undefined
}
```

**Comment by Deivu** [comment]
@kaname-png seems like the issue is something network related, do you use a proxy of some sort, seems like your server can't connect via HTTP to listen.moe

**Comment by kaname-png** [comment]
No, I do not use any proxy or vpn, I do not know why I will have that problem

The weird thing is that after 2 seconds the client tells me that it was able to successfully reconnect to the listen.moe server

**Comment by Deivu** [comment]
Hmm, so basically after that, you are able to continue on your connection or something?

**Comment by kaname-png** [comment]
Yes, everything works normally afterwards, it only happens when trying to connect for the first time

**Comment by Deivu** [comment]
If this is the case I guess it should be fine, the issue comes from network most likely, but since it reconnects it should be fine, you can report back once it fails to reconnect after a lot of times again, if it reconnects fine then most likely this is just a network issue of some sort, though I can't really tell where it originates from the network tho

**Comment by kaname-png** [comment]
Well, that's fine with me, thank you very much.
